Repository BARlSTAS/test-bucket, pull requests merged in 2020-08, with the labels that each got.

#2 브랜치 배포 전략 추가
  README.md
Labels: documentation, enhancement, hotfix

#1 타입스크립트를 포함한 컴파일 시 build file이 생성되는 프로젝트를 위한 ignore
  .gitignore
Labels: chore, enhancement, hotfix

#5 chore: add FEATURE_REQUEST_TEMPLATE.md
  .github/ISSUE_TEMPLATE/FEATURE_REQUEST_TEMPLATE.md
Labels: chore, documentation

#4 Pull Request Template 추가
  .github/PULL_REQUEST_TEMPLATE.md
  docs/mocha_pr_template_ko.md
Labels: chore, documentation, enhancement

#8 Hotfix/support question template
  .github/ISSUE_TEMPLATE/FEATURE_REQUEST_TEMPLATE.md
  .github/ISSUE_TEMPLATE/SUPPORT_QUESTIONS_TEMPLATE.md
Labels: chore, documentation, enhancement
